Traceback (most recent call last):
  File "/home/acalc79/synced/part-ii-project/dlti_scripts/preprocessing/util.py", line 57, in extract_dir
    extraction_function(pypath, outpath)
  File "/home/acalc79/synced/part-ii-project/dlti_scripts/preprocessing/core/syntactic/extract.py", line 88, in extract_all_syntactic_contexts
    silent_errors)
  File "/home/acalc79/synced/part-ii-project/dlti_scripts/preprocessing/core/syntactic/extract.py", line 74, in get_all_syntactic_contexts
    for pos in new_occurences]
  File "/home/acalc79/synced/part-ii-project/dlti_scripts/preprocessing/core/syntactic/extract.py", line 74, in <listcomp>
    for pos in new_occurences]
  File "/home/acalc79/synced/part-ii-project/dlti_scripts/preprocessing/core/context/extract.py", line 27, in get_context
    raise
AttributeError: 'alias' object has no attribute 'lineno'

Source: data/repos/allennlp/allennlp/common/params.py


Traceback (most recent call last):
  File "/home/acalc79/synced/part-ii-project/dlti_scripts/preprocessing/util.py", line 57, in extract_dir
    extraction_function(pypath, outpath)
  File "/home/acalc79/synced/part-ii-project/dlti_scripts/preprocessing/core/syntactic/extract.py", line 88, in extract_all_syntactic_contexts
    silent_errors)
  File "/home/acalc79/synced/part-ii-project/dlti_scripts/preprocessing/core/syntactic/extract.py", line 74, in get_all_syntactic_contexts
    for pos in new_occurences]
  File "/home/acalc79/synced/part-ii-project/dlti_scripts/preprocessing/core/syntactic/extract.py", line 74, in <listcomp>
    for pos in new_occurences]
  File "/home/acalc79/synced/part-ii-project/dlti_scripts/preprocessing/core/context/extract.py", line 27, in get_context
    raise
AttributeError: 'alias' object has no attribute 'lineno'

Source: data/repos/zulip/zerver/lib/management.py


Traceback (most recent call last):
  File "/home/acalc79/synced/part-ii-project/dlti_scripts/preprocessing/util.py", line 57, in extract_dir
    extraction_function(pypath, outpath)
  File "/home/acalc79/synced/part-ii-project/dlti_scripts/preprocessing/core/syntactic/extract.py", line 88, in extract_all_syntactic_contexts
    silent_errors)
  File "/home/acalc79/synced/part-ii-project/dlti_scripts/preprocessing/core/syntactic/extract.py", line 74, in get_all_syntactic_contexts
    for pos in new_occurences]
  File "/home/acalc79/synced/part-ii-project/dlti_scripts/preprocessing/core/syntactic/extract.py", line 74, in <listcomp>
    for pos in new_occurences]
  File "/home/acalc79/synced/part-ii-project/dlti_scripts/preprocessing/core/context/extract.py", line 23, in get_context
    try:
  File "/home/acalc79/synced/part-ii-project/dlti_scripts/preprocessing/core/ast_util.py", line 57, in get_node
    return get_node(child[i], pos[2:])
  File "/home/acalc79/synced/part-ii-project/dlti_scripts/preprocessing/core/ast_util.py", line 57, in get_node
    return get_node(child[i], pos[2:])
  File "/home/acalc79/synced/part-ii-project/dlti_scripts/preprocessing/core/ast_util.py", line 57, in get_node
    return get_node(child[i], pos[2:])
  File "/home/acalc79/synced/part-ii-project/dlti_scripts/preprocessing/core/ast_util.py", line 48, in get_node
    child = getattr(node, pos[0])
AttributeError: ("'If' object has no attribute 'target'", ('target',), ('body', 0, 'target'), ('body', 3, 'body', 0, 'target'), ('body', 9, 'body', 3, 'body', 0, 'target'))

Source: data/repos/sslyze/sslyze/utils/ssl_connection_configurator.py


Traceback (most recent call last):
  File "/home/acalc79/synced/part-ii-project/dlti_scripts/preprocessing/util.py", line 57, in extract_dir
    extraction_function(pypath, outpath)
  File "/home/acalc79/synced/part-ii-project/dlti_scripts/preprocessing/core/syntactic/extract.py", line 88, in extract_all_syntactic_contexts
    silent_errors)
  File "/home/acalc79/synced/part-ii-project/dlti_scripts/preprocessing/core/syntactic/extract.py", line 74, in get_all_syntactic_contexts
    for pos in new_occurences]
  File "/home/acalc79/synced/part-ii-project/dlti_scripts/preprocessing/core/syntactic/extract.py", line 74, in <listcomp>
    for pos in new_occurences]
  File "/home/acalc79/synced/part-ii-project/dlti_scripts/preprocessing/core/context/extract.py", line 23, in get_context
    try:
  File "/home/acalc79/synced/part-ii-project/dlti_scripts/preprocessing/core/ast_util.py", line 57, in get_node
    return get_node(child[i], pos[2:])
  File "/home/acalc79/synced/part-ii-project/dlti_scripts/preprocessing/core/ast_util.py", line 57, in get_node
    return get_node(child[i], pos[2:])
  File "/home/acalc79/synced/part-ii-project/dlti_scripts/preprocessing/core/ast_util.py", line 48, in get_node
    child = getattr(node, pos[0])
AttributeError: ("'Assign' object has no attribute 'target'", ('target',), ('body', 13, 'target'), ('body', 22, 'body', 13, 'target'))

Source: data/repos/orange3/Orange/widgets/data/owfile.py


Traceback (most recent call last):
  File "/home/acalc79/synced/part-ii-project/dlti_scripts/preprocessing/util.py", line 57, in extract_dir
    extraction_function(pypath, outpath)
  File "/home/acalc79/synced/part-ii-project/dlti_scripts/preprocessing/core/syntactic/extract.py", line 88, in extract_all_syntactic_contexts
    silent_errors)
  File "/home/acalc79/synced/part-ii-project/dlti_scripts/preprocessing/core/syntactic/extract.py", line 74, in get_all_syntactic_contexts
    for pos in new_occurences]
  File "/home/acalc79/synced/part-ii-project/dlti_scripts/preprocessing/core/syntactic/extract.py", line 74, in <listcomp>
    for pos in new_occurences]
  File "/home/acalc79/synced/part-ii-project/dlti_scripts/preprocessing/core/context/extract.py", line 23, in get_context
    try:
  File "/home/acalc79/synced/part-ii-project/dlti_scripts/preprocessing/core/ast_util.py", line 57, in get_node
    return get_node(child[i], pos[2:])
  File "/home/acalc79/synced/part-ii-project/dlti_scripts/preprocessing/core/ast_util.py", line 57, in get_node
    return get_node(child[i], pos[2:])
  File "/home/acalc79/synced/part-ii-project/dlti_scripts/preprocessing/core/ast_util.py", line 48, in get_node
    child = getattr(node, pos[0])
AttributeError: ("'If' object has no attribute 'target'", ('target',), ('body', 1, 'target'), ('body', 20, 'body', 1, 'target'))

Source: data/repos/golem/apps/rendering/task/framerenderingtask.py


Traceback (most recent call last):
  File "/home/acalc79/synced/part-ii-project/dlti_scripts/preprocessing/util.py", line 57, in extract_dir
    extraction_function(pypath, outpath)
  File "/home/acalc79/synced/part-ii-project/dlti_scripts/preprocessing/core/syntactic/extract.py", line 88, in extract_all_syntactic_contexts
    silent_errors)
  File "/home/acalc79/synced/part-ii-project/dlti_scripts/preprocessing/core/syntactic/extract.py", line 74, in get_all_syntactic_contexts
    for pos in new_occurences]
  File "/home/acalc79/synced/part-ii-project/dlti_scripts/preprocessing/core/syntactic/extract.py", line 74, in <listcomp>
    for pos in new_occurences]
  File "/home/acalc79/synced/part-ii-project/dlti_scripts/preprocessing/core/context/extract.py", line 27, in get_context
    raise
AttributeError: 'alias' object has no attribute 'lineno'

Source: data/repos/rasa_core/rasa_core/training/generator.py


Traceback (most recent call last):
  File "/home/acalc79/synced/part-ii-project/dlti_scripts/preprocessing/util.py", line 57, in extract_dir
    extraction_function(pypath, outpath)
  File "/home/acalc79/synced/part-ii-project/dlti_scripts/preprocessing/core/syntactic/extract.py", line 88, in extract_all_syntactic_contexts
    silent_errors)
  File "/home/acalc79/synced/part-ii-project/dlti_scripts/preprocessing/core/syntactic/extract.py", line 74, in get_all_syntactic_contexts
    for pos in new_occurences]
  File "/home/acalc79/synced/part-ii-project/dlti_scripts/preprocessing/core/syntactic/extract.py", line 74, in <listcomp>
    for pos in new_occurences]
  File "/home/acalc79/synced/part-ii-project/dlti_scripts/preprocessing/core/context/extract.py", line 27, in get_context
    raise
AttributeError: 'alias' object has no attribute 'lineno'

Source: data/repos/RxPY/rx/core/blockingobservable.py


Traceback (most recent call last):
  File "/home/acalc79/synced/part-ii-project/dlti_scripts/preprocessing/util.py", line 57, in extract_dir
    extraction_function(pypath, outpath)
  File "/home/acalc79/synced/part-ii-project/dlti_scripts/preprocessing/core/syntactic/extract.py", line 88, in extract_all_syntactic_contexts
    silent_errors)
  File "/home/acalc79/synced/part-ii-project/dlti_scripts/preprocessing/core/syntactic/extract.py", line 74, in get_all_syntactic_contexts
    for pos in new_occurences]
  File "/home/acalc79/synced/part-ii-project/dlti_scripts/preprocessing/core/syntactic/extract.py", line 74, in <listcomp>
    for pos in new_occurences]
  File "/home/acalc79/synced/part-ii-project/dlti_scripts/preprocessing/core/context/extract.py", line 27, in get_context
    raise
AttributeError: 'alias' object has no attribute 'lineno'

Source: data/repos/RxPY/rx/core/observerbase.py


Traceback (most recent call last):
  File "/home/acalc79/synced/part-ii-project/dlti_scripts/preprocessing/util.py", line 57, in extract_dir
    extraction_function(pypath, outpath)
  File "/home/acalc79/synced/part-ii-project/dlti_scripts/preprocessing/core/syntactic/extract.py", line 88, in extract_all_syntactic_contexts
    silent_errors)
  File "/home/acalc79/synced/part-ii-project/dlti_scripts/preprocessing/core/syntactic/extract.py", line 74, in get_all_syntactic_contexts
    for pos in new_occurences]
  File "/home/acalc79/synced/part-ii-project/dlti_scripts/preprocessing/core/syntactic/extract.py", line 74, in <listcomp>
    for pos in new_occurences]
  File "/home/acalc79/synced/part-ii-project/dlti_scripts/preprocessing/core/context/extract.py", line 27, in get_context
    raise
AttributeError: 'alias' object has no attribute 'lineno'

Source: data/repos/RxPY/rx/core/observablebase.py


Traceback (most recent call last):
  File "/home/acalc79/synced/part-ii-project/dlti_scripts/preprocessing/util.py", line 57, in extract_dir
    extraction_function(pypath, outpath)
  File "/home/acalc79/synced/part-ii-project/dlti_scripts/preprocessing/core/syntactic/extract.py", line 88, in extract_all_syntactic_contexts
    silent_errors)
  File "/home/acalc79/synced/part-ii-project/dlti_scripts/preprocessing/core/syntactic/extract.py", line 74, in get_all_syntactic_contexts
    for pos in new_occurences]
  File "/home/acalc79/synced/part-ii-project/dlti_scripts/preprocessing/core/syntactic/extract.py", line 74, in <listcomp>
    for pos in new_occurences]
  File "/home/acalc79/synced/part-ii-project/dlti_scripts/preprocessing/core/context/extract.py", line 27, in get_context
    raise
AttributeError: 'alias' object has no attribute 'lineno'

Source: data/repos/RxPY/rx/core/observable.py


Traceback (most recent call last):
  File "/home/acalc79/synced/part-ii-project/dlti_scripts/preprocessing/util.py", line 57, in extract_dir
    extraction_function(pypath, outpath)
  File "/home/acalc79/synced/part-ii-project/dlti_scripts/preprocessing/core/syntactic/extract.py", line 88, in extract_all_syntactic_contexts
    silent_errors)
  File "/home/acalc79/synced/part-ii-project/dlti_scripts/preprocessing/core/syntactic/extract.py", line 74, in get_all_syntactic_contexts
    for pos in new_occurences]
  File "/home/acalc79/synced/part-ii-project/dlti_scripts/preprocessing/core/syntactic/extract.py", line 74, in <listcomp>
    for pos in new_occurences]
  File "/home/acalc79/synced/part-ii-project/dlti_scripts/preprocessing/core/context/extract.py", line 23, in get_context
    try:
  File "/home/acalc79/synced/part-ii-project/dlti_scripts/preprocessing/core/ast_util.py", line 57, in get_node
    return get_node(child[i], pos[2:])
  File "/home/acalc79/synced/part-ii-project/dlti_scripts/preprocessing/core/ast_util.py", line 57, in get_node
    return get_node(child[i], pos[2:])
  File "/home/acalc79/synced/part-ii-project/dlti_scripts/preprocessing/core/ast_util.py", line 48, in get_node
    child = getattr(node, pos[0])
AttributeError: ("'Assign' object has no attribute 'target'", ('target',), ('body', 2, 'target'), ('body', 2, 'body', 2, 'target'))

Source: data/repos/cython/tests/run/pure_parallel.py


Traceback (most recent call last):
  File "/home/acalc79/synced/part-ii-project/dlti_scripts/preprocessing/util.py", line 57, in extract_dir
    extraction_function(pypath, outpath)
  File "/home/acalc79/synced/part-ii-project/dlti_scripts/preprocessing/core/syntactic/extract.py", line 88, in extract_all_syntactic_contexts
    silent_errors)
  File "/home/acalc79/synced/part-ii-project/dlti_scripts/preprocessing/core/syntactic/extract.py", line 74, in get_all_syntactic_contexts
    for pos in new_occurences]
  File "/home/acalc79/synced/part-ii-project/dlti_scripts/preprocessing/core/syntactic/extract.py", line 74, in <listcomp>
    for pos in new_occurences]
  File "/home/acalc79/synced/part-ii-project/dlti_scripts/preprocessing/core/context/extract.py", line 27, in get_context
    raise
AttributeError: 'alias' object has no attribute 'lineno'

Source: data/repos/mypy/test-data/stdlib-samples/3.2/test/test_glob.py


Traceback (most recent call last):
  File "/home/acalc79/synced/part-ii-project/dlti_scripts/preprocessing/util.py", line 57, in extract_dir
    extraction_function(pypath, outpath)
  File "/home/acalc79/synced/part-ii-project/dlti_scripts/preprocessing/core/syntactic/extract.py", line 88, in extract_all_syntactic_contexts
    silent_errors)
  File "/home/acalc79/synced/part-ii-project/dlti_scripts/preprocessing/core/syntactic/extract.py", line 74, in get_all_syntactic_contexts
    for pos in new_occurences]
  File "/home/acalc79/synced/part-ii-project/dlti_scripts/preprocessing/core/syntactic/extract.py", line 74, in <listcomp>
    for pos in new_occurences]
  File "/home/acalc79/synced/part-ii-project/dlti_scripts/preprocessing/core/context/extract.py", line 27, in get_context
    raise
AttributeError: 'alias' object has no attribute 'lineno'

Source: data/repos/mypy/mypy/plugins/attrs.py


Traceback (most recent call last):
  File "/home/acalc79/synced/part-ii-project/dlti_scripts/preprocessing/util.py", line 57, in extract_dir
    extraction_function(pypath, outpath)
  File "/home/acalc79/synced/part-ii-project/dlti_scripts/preprocessing/core/syntactic/extract.py", line 88, in extract_all_syntactic_contexts
    silent_errors)
  File "/home/acalc79/synced/part-ii-project/dlti_scripts/preprocessing/core/syntactic/extract.py", line 74, in get_all_syntactic_contexts
    for pos in new_occurences]
  File "/home/acalc79/synced/part-ii-project/dlti_scripts/preprocessing/core/syntactic/extract.py", line 74, in <listcomp>
    for pos in new_occurences]
  File "/home/acalc79/synced/part-ii-project/dlti_scripts/preprocessing/core/context/extract.py", line 27, in get_context
    raise
AttributeError: 'alias' object has no attribute 'lineno'

Source: data/repos/mypy/mypy/test/testfinegrained.py


Traceback (most recent call last):
  File "/home/acalc79/synced/part-ii-project/dlti_scripts/preprocessing/util.py", line 57, in extract_dir
    extraction_function(pypath, outpath)
  File "/home/acalc79/synced/part-ii-project/dlti_scripts/preprocessing/core/syntactic/extract.py", line 88, in extract_all_syntactic_contexts
    silent_errors)
  File "/home/acalc79/synced/part-ii-project/dlti_scripts/preprocessing/core/syntactic/extract.py", line 74, in get_all_syntactic_contexts
    for pos in new_occurences]
  File "/home/acalc79/synced/part-ii-project/dlti_scripts/preprocessing/core/syntactic/extract.py", line 74, in <listcomp>
    for pos in new_occurences]
  File "/home/acalc79/synced/part-ii-project/dlti_scripts/preprocessing/core/context/extract.py", line 27, in get_context
    raise
AttributeError: 'alias' object has no attribute 'lineno'

Source: data/repos/mypy/mypy/test/testdiff.py


Traceback (most recent call last):
  File "/home/acalc79/synced/part-ii-project/dlti_scripts/preprocessing/util.py", line 57, in extract_dir
    extraction_function(pypath, outpath)
  File "/home/acalc79/synced/part-ii-project/dlti_scripts/preprocessing/core/syntactic/extract.py", line 88, in extract_all_syntactic_contexts
    silent_errors)
  File "/home/acalc79/synced/part-ii-project/dlti_scripts/preprocessing/core/syntactic/extract.py", line 74, in get_all_syntactic_contexts
    for pos in new_occurences]
  File "/home/acalc79/synced/part-ii-project/dlti_scripts/preprocessing/core/syntactic/extract.py", line 74, in <listcomp>
    for pos in new_occurences]
  File "/home/acalc79/synced/part-ii-project/dlti_scripts/preprocessing/core/context/extract.py", line 27, in get_context
    raise
AttributeError: 'alias' object has no attribute 'lineno'

Source: data/repos/mypy/mypy/test/testdeps.py


